version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  web:
    image: jedi-cycles-api
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      - webnet
    environment:
          REDIS_HOST: redis
          REDIS_PORT: 6379
          DOCKER_VERSION: '3'
    depends_on:
      - 'redis'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
      interval: 1m30s
      timeout: 10s
      retries: 3
networks:
  webnet:
